# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/config.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(640, 530)
        self.verticalLayout_8 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listWidget = QtGui.QListWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(85, 16777215))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setAutoScroll(True)
        self.listWidget.setIconSize(QtCore.QSize(75, 75))
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/mail.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/chat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/blacklist.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_10 = QtGui.QGroupBox(self.page)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalSlider_interval = QtGui.QSlider(self.groupBox_10)
        self.horizontalSlider_interval.setMaximum(20)
        self.horizontalSlider_interval.setPageStep(1)
        self.horizontalSlider_interval.setProperty("value", 0)
        self.horizontalSlider_interval.setSliderPosition(0)
        self.horizontalSlider_interval.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_interval.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_interval.setObjectName(_fromUtf8("horizontalSlider_interval"))
        self.gridLayout_2.addWidget(self.horizontalSlider_interval, 0, 1, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox_10)
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 2, 1, 1)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.groupBox_10)
        self.lcdNumber_2.setDigitCount(4)
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 5.0)
        self.lcdNumber_2.setProperty("intValue", 5)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_2, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_10)
        self.label.setWhatsThis(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_10)
        self.label_2.setWhatsThis(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalSlider_timeaut = QtGui.QSlider(self.groupBox_10)
        self.horizontalSlider_timeaut.setMinimum(5)
        self.horizontalSlider_timeaut.setMaximum(100)
        self.horizontalSlider_timeaut.setSingleStep(5)
        self.horizontalSlider_timeaut.setPageStep(5)
        self.horizontalSlider_timeaut.setProperty("value", 5)
        self.horizontalSlider_timeaut.setSliderPosition(5)
        self.horizontalSlider_timeaut.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_timeaut.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_timeaut.setObjectName(_fromUtf8("horizontalSlider_timeaut"))
        self.gridLayout_2.addWidget(self.horizontalSlider_timeaut, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.groupBox_10)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.checkBox_Blacklist = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_Blacklist.setChecked(True)
        self.checkBox_Blacklist.setObjectName(_fromUtf8("checkBox_Blacklist"))
        self.verticalLayout_4.addWidget(self.checkBox_Blacklist)
        self.checkBox_repeat = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_repeat.setObjectName(_fromUtf8("checkBox_repeat"))
        self.verticalLayout_4.addWidget(self.checkBox_repeat)
        self.verticalLayout_11.addWidget(self.groupBox_10)
        self.groupBox_9 = QtGui.QGroupBox(self.page)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButton_ramdom = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_ramdom.setChecked(True)
        self.radioButton_ramdom.setObjectName(_fromUtf8("radioButton_ramdom"))
        self.horizontalLayout_6.addWidget(self.radioButton_ramdom)
        self.radioButton_order = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_order.setObjectName(_fromUtf8("radioButton_order"))
        self.horizontalLayout_6.addWidget(self.radioButton_order)
        self.radioButton_one = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_one.setStyleSheet(_fromUtf8(""))
        self.radioButton_one.setObjectName(_fromUtf8("radioButton_one"))
        self.horizontalLayout_6.addWidget(self.radioButton_one)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addWidget(self.groupBox_9)
        self.groupBox_4 = QtGui.QGroupBox(self.page)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.comboBox_one_letter = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_one_letter.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_one_letter.setObjectName(_fromUtf8("comboBox_one_letter"))
        self.comboBox_one_letter.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.comboBox_one_letter)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.comboBox_one_msg = QtGui.QComboBox(self.groupBox)
        self.comboBox_one_msg.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_one_msg.setObjectName(_fromUtf8("comboBox_one_msg"))
        self.comboBox_one_msg.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.comboBox_one_msg)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_7 = QtGui.QGroupBox(self.page)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.comboBox_style = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_style.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_style.setObjectName(_fromUtf8("comboBox_style"))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.comboBox_style.addItem(_fromUtf8(""))
        self.verticalLayout_14.addWidget(self.comboBox_style)
        self.verticalLayout_11.addWidget(self.groupBox_7)
        spacerItem = QtGui.QSpacerItem(20, 42, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_5 = QtGui.QGroupBox(self.page_1)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listWidgetPic = QtGui.QListWidget(self.groupBox_5)
        self.listWidgetPic.setIconSize(QtCore.QSize(96, 84))
        self.listWidgetPic.setMovement(QtGui.QListView.Static)
        self.listWidgetPic.setFlow(QtGui.QListView.LeftToRight)
        self.listWidgetPic.setProperty("isWrapping", True)
        self.listWidgetPic.setResizeMode(QtGui.QListView.Adjust)
        self.listWidgetPic.setViewMode(QtGui.QListView.IconMode)
        self.listWidgetPic.setWordWrap(True)
        self.listWidgetPic.setObjectName(_fromUtf8("listWidgetPic"))
        item = QtGui.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/no_photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable)
        self.listWidgetPic.addItem(item)
        self.horizontalLayout_3.addWidget(self.listWidgetPic)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plainTextEdit_letter_subject = QtGui.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_letter_subject.setMaximumSize(QtCore.QSize(16777215, 120))
        self.plainTextEdit_letter_subject.setObjectName(_fromUtf8("plainTextEdit_letter_subject"))
        self.verticalLayout_2.addWidget(self.plainTextEdit_letter_subject)
        self.plainTextEdit_letter_body = QtGui.QPlainTextEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEdit_letter_body.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_letter_body.setSizePolicy(sizePolicy)
        self.plainTextEdit_letter_body.setObjectName(_fromUtf8("plainTextEdit_letter_body"))
        self.verticalLayout_2.addWidget(self.plainTextEdit_letter_body)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_3 = QtGui.QGroupBox(self.page_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.plainTextEdit_msg = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_msg.setObjectName(_fromUtf8("plainTextEdit_msg"))
        self.verticalLayout_9.addWidget(self.plainTextEdit_msg)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.page_4)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.plainTextEdit_chat_blacklist = QtGui.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_chat_blacklist.setPlainText(_fromUtf8(""))
        self.plainTextEdit_chat_blacklist.setObjectName(_fromUtf8("plainTextEdit_chat_blacklist"))
        self.verticalLayout_12.addWidget(self.plainTextEdit_chat_blacklist)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_8 = QtGui.QGroupBox(self.page_4)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.plainTextEdit_admirer_blacklist = QtGui.QPlainTextEdit(self.groupBox_8)
        self.plainTextEdit_admirer_blacklist.setPlainText(_fromUtf8(""))
        self.plainTextEdit_admirer_blacklist.setObjectName(_fromUtf8("plainTextEdit_admirer_blacklist"))
        self.verticalLayout_15.addWidget(self.plainTextEdit_admirer_blacklist)
        self.horizontalLayout_4.addWidget(self.groupBox_8)
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QListWidgetItem*,QListWidgetItem*)")), Dialog.changePage)
        QtCore.QObject.connect(self.horizontalSlider_timeaut, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_2.display)
        QtCore.QObject.connect(self.horizontalSlider_interval, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.applySettings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.horizontalSlider_interval, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Dialog.on_interval_changed)
        QtCore.QObject.connect(self.horizontalSlider_timeaut, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Dialog.on_timeaut_changed)
        QtCore.QObject.connect(self.checkBox_Blacklist, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Dialog.on_blacklist_state_changed)
        QtCore.QObject.connect(self.checkBox_repeat, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Dialog.on_repeat_state_changed)
        QtCore.QObject.connect(self.radioButton_ramdom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Dialog.on_mode1_changed)
        QtCore.QObject.connect(self.radioButton_order, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Dialog.on_mode2_changed)
        QtCore.QObject.connect(self.radioButton_one, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Dialog.on_mode3_changed)
        QtCore.QObject.connect(self.comboBox_one_msg, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.on_one_msg_index_changed)
        QtCore.QObject.connect(self.comboBox_one_letter, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.on_one_letter_index_changed)
        QtCore.QObject.connect(self.listWidgetPic, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), Dialog.on_photo_changed)
        QtCore.QObject.connect(self.plainTextEdit_letter_subject, QtCore.SIGNAL(_fromUtf8("textChanged()")), Dialog.on_letter_subject_changed)
        QtCore.QObject.connect(self.plainTextEdit_letter_body, QtCore.SIGNAL(_fromUtf8("textChanged()")), Dialog.on_letter_body_changed)
        QtCore.QObject.connect(self.plainTextEdit_msg, QtCore.SIGNAL(_fromUtf8("textChanged()")), Dialog.on_msg_body_changed)
        QtCore.QObject.connect(self.comboBox_one_msg, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.on_one_msg_index_changed_int)
        QtCore.QObject.connect(self.comboBox_one_letter, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.on_one_letter_index_changed_int)
        QtCore.QObject.connect(self.comboBox_style, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.on_style_changed)
        QtCore.QObject.connect(self.plainTextEdit_chat_blacklist, QtCore.SIGNAL(_fromUtf8("textChanged()")), Dialog.on_chat_blacklist_body_changed)
        QtCore.QObject.connect(self.plainTextEdit_admirer_blacklist, QtCore.SIGNAL(_fromUtf8("textChanged()")), Dialog.on_admirer_blacklist_body_changed)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Настройки программы", None))
        self.listWidget.setWhatsThis(_translate("Dialog", "Основные настройки программы", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "Основные", None))
        item.setWhatsThis(_translate("Dialog", "Основные настройки программы", None))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "Фото", None))
        item.setWhatsThis(_translate("Dialog", "Выбор отправляемого в письме фото", None))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "Письма", None))
        item.setWhatsThis(_translate("Dialog", "Шаблоны отправляемых писем поклонникам", None))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "Сообщения", None))
        item.setWhatsThis(_translate("Dialog", "Шаблоны отправляемых сообщений в чат", None))
        item = self.listWidget.item(4)
        item.setText(_translate("Dialog", "Блэклист", None))
        item.setWhatsThis(_translate("Dialog", "Черный список, тех кому мы ничего не шлем", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_10.setTitle(_translate("Dialog", "Настройка рассылки", None))
        self.horizontalSlider_interval.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Интервал между рассылками.</span></p><p><span style=\" font-size:10pt;\">Активно если установлен режим &quot;</span><span style=\" font-size:10pt; font-weight:600;\">ПО ПОРЯДКУ&quot;</span><span style=\" font-size:10pt;\">.</span></p><p><span style=\" font-size:10pt;\">Устанавливает интервал в секундах между циклами рассылок.</span></p><p><span style=\" font-size:10pt;\">То есть, когда программа сделает рассылку первого письма по всем мужчинам онлайн, то перед тем как начинать рассылать второе письмо, программа будет ждать заданное число секунд до начала следующей рассылки.</span></p></body></html>", None))
        self.horizontalSlider_interval.setWhatsThis(_translate("Dialog", "Интервал между рассылками (мин.)", None))
        self.label.setText(_translate("Dialog", "Интервал между рассылками (мин.)", None))
        self.label_2.setText(_translate("Dialog", "Таймаут между сообщениями (сек.)", None))
        self.horizontalSlider_timeaut.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Таймаут между сообщениями</span></p><p><span style=\" font-size:10pt;\">Устанавливает интервал в секундах между отправкой каждого сообщения / письма.</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Не рекомендуется ставить маленький таймаут! </span></p><p><span style=\" font-size:10pt;\">Сервер может посчитать что вы бот и отбрасывать ваши сообщения.</span></p></body></html>", None))
        self.horizontalSlider_timeaut.setWhatsThis(_translate("Dialog", "Таймаут между сообщениями (сек.)", None))
        self.checkBox_Blacklist.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Включает черный список. </span></p><p><span style=\" font-size:10pt;\">Изменения применяются сразу после закрытия окна настроек. </span></p><p><span style=\" font-size:10pt;\">Если рассылка уже работает, изменения вступят в силу только после перезапуска расылки.</span></p></body></html>", None))
        self.checkBox_Blacklist.setWhatsThis(_translate("Dialog", "Включить черный список", None))
        self.checkBox_Blacklist.setText(_translate("Dialog", "&Черный список", None))
        self.checkBox_repeat.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Активирует режим повтора рассылки. </span></p><p><span style=\" font-size:10pt;\">Если режим активен, после нажатия кнопки </span><span style=\" font-size:10pt; font-weight:600;\">&quot;ПУСК&quot;</span><span style=\" font-size:10pt;\">, расылка будет повторяться бесконечно.</span></p></body></html>", None))
        self.checkBox_repeat.setWhatsThis(_translate("Dialog", "Включить повтор рассылки", None))
        self.checkBox_repeat.setText(_translate("Dialog", "&Повторять рассылку", None))
        self.groupBox_9.setWhatsThis(_translate("Dialog", "Выбор режима работы", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Выбор режима работы", None))
        self.radioButton_ramdom.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Отправлять случайно выбранное из шаблонов письмо (сообщение).</span></p></body></html>", None))
        self.radioButton_ramdom.setWhatsThis(_translate("Dialog", "Всем отправляется случайно выбранное из шаблонов письмо", None))
        self.radioButton_ramdom.setText(_translate("Dialog", "&СЛУЧАЙНО", None))
        self.radioButton_order.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Все письма отправляются по порядку, начиная с первого.</span></p><p><span style=\" font-size:10pt;\">Если выбрано письмо в разделе </span><span style=\" font-size:10pt; font-weight:600;\">&quot;Отправлять это письмо (начать с этого письма)&quot;</span><span style=\" font-size:10pt;\">, то отправка начнется с этого письма!</span></p></body></html>", None))
        self.radioButton_order.setWhatsThis(_translate("Dialog", "Все письма отправляются по порядку, начиная с первого.\n"
"Если выбрано письмо в разделе \"Отправлять это письмо / Начать с этого письма\", то отправка начнется с этого письма.", None))
        self.radioButton_order.setText(_translate("Dialog", "ПО &ПОРЯДКУ", None))
        self.radioButton_one.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Отправлять только одно письмо</span></p><p><span style=\" font-size:10pt;\">Будет отправляться письмо, выбранное в разделе  </span><span style=\" font-size:10pt; font-weight:600;\">&quot;Отправлять это письмо (начать с этого письма)&quot;.</span></p></body></html>", None))
        self.radioButton_one.setText(_translate("Dialog", "&ОДНО ПИСЬМО (СООБЩ.)", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Отправлять это письмо ( начать с этого письма)", None))
        self.comboBox_one_letter.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Отправлять это письмо (начать с этого письма)</span></p><p><span style=\" font-size:10pt;\">Если активен режим </span><span style=\" font-size:10pt; font-weight:600;\">&quot;ПО ПОРЯДКУ&quot;</span><span style=\" font-size:10pt;\">, отправка начинается с текущего письма. </span></p><p><span style=\" font-size:10pt;\">При активном режиме </span><span style=\" font-size:10pt; font-weight:600;\">&quot;ОДНО ПИСЬМО (СООБЩ.)&quot;</span><span style=\" font-size:10pt;\"> всем отправляется это письмо. </span></p></body></html>", None))
        self.comboBox_one_letter.setWhatsThis(_translate("Dialog", "Отправка начинается с текущего сообщения, если активен режим \"По порядку\". Или всем отправляется только выбранное письмо при активном режиме \"Одно письмо\".", None))
        self.comboBox_one_letter.setItemText(0, _translate("Dialog", "Пример письма №1. Письмо должно содержать не менее 200 символов.", None))
        self.groupBox.setTitle(_translate("Dialog", "Отправлять это сообщения (начать с этого сообщения)", None))
        self.comboBox_one_msg.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Отправлять это сообщения (начать с этого сообщения)</span></p><p><span style=\" font-size:10pt;\">Если активен режим </span><span style=\" font-size:10pt; font-weight:600;\">&quot;ПО ПОРЯДКУ&quot;</span><span style=\" font-size:10pt;\">, отправка начинается с текущего сообщения. </span></p><p><span style=\" font-size:10pt;\">При активном режиме </span><span style=\" font-size:10pt; font-weight:600;\">&quot;ОДНО ПИСЬМО (СООБЩ.)&quot;</span><span style=\" font-size:10pt;\"> всем отправляется это сообщение. </span></p></body></html>", None))
        self.comboBox_one_msg.setWhatsThis(_translate("Dialog", "Отправка начинается с текущего сообщения, если активен режим \"По порядку\". Или всем отправляется только выбранное письмо при активном режиме \"Одно письмо\".", None))
        self.comboBox_one_msg.setItemText(0, _translate("Dialog", "Пример сообщения в чат №1. Обратите внимание на точку с запятой в конце письма. Так мы разделяем одно сообщение от другого;", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Стиль приложения", None))
        self.comboBox_style.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Изменить стиль приложения</span></p><p><span style=\" font-size:10pt;\">Изменения вступят в силу после перезапуска программы.</span></p></body></html>", None))
        self.comboBox_style.setWhatsThis(_translate("Dialog", "Стиль приложения. Для применения изменений требуется перезапуск приложения.", None))
        self.comboBox_style.setItemText(0, _translate("Dialog", "Plastique (по умолчанию)", None))
        self.comboBox_style.setItemText(1, _translate("Dialog", "Системная (без темы)", None))
        self.comboBox_style.setItemText(2, _translate("Dialog", "Cleanlooks", None))
        self.comboBox_style.setItemText(3, _translate("Dialog", "Windows", None))
        self.comboBox_style.setItemText(4, _translate("Dialog", "Mac", None))
        self.comboBox_style.setItemText(5, _translate("Dialog", "Sgi", None))
        self.comboBox_style.setItemText(6, _translate("Dialog", "Cde", None))
        self.comboBox_style.setItemText(7, _translate("Dialog", "Motif", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Выбрать фото", None))
        self.listWidgetPic.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Снять выделение фото</span></p></body></html>", None))
        self.listWidgetPic.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Отменить выделение</p></body></html>", None))
        __sortingEnabled = self.listWidgetPic.isSortingEnabled()
        self.listWidgetPic.setSortingEnabled(False)
        item = self.listWidgetPic.item(0)
        item.setText(_translate("Dialog", "no photo", None))
        self.listWidgetPic.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("Dialog", "Отправки письма", None))
        self.plainTextEdit_letter_subject.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Заголовок отправляемого письма</span></p><p><span style=\" font-size:10pt;\">Если число заголовков равно числу писем, то первый заголовок будет отправлен с первым письмом. </span></p><p><span style=\" font-size:10pt;\">Если заголовков больше или меньше, заголовок к письму будет выбран случайно.</span></p></body></html>", None))
        self.plainTextEdit_letter_subject.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Заголовки писем</p></body></html>", None))
        self.plainTextEdit_letter_subject.setPlainText(_translate("Dialog", "Пример заголовка 1\n"
"======\n"
"Пример заголовка 2\n"
"======\n"
"Пример заголовка 3", None))
        self.plainTextEdit_letter_body.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Шаблоны писем</span></p><p><span style=\" font-size:10pt;\">Сюда вставляем шаблоны писем для отправки поклонникам. Обратите внимание на знаки рано </span><span style=\" font-size:10pt; font-weight:600;\">&quot;=&quot;</span><span style=\" font-size:10pt;\"> в конце письма. Так мы разделяем одно письмо от другого. Знаков разделения может быть любое количество.</span></p><p><span style=\" font-size:10pt;\">Если вставить в письмо переменную </span><span style=\" font-size:10pt; font-weight:600;\">%name%</span><span style=\" font-size:10pt;\">, она будет автоматически заменена на имя мужчины. Каждое письмо должно содержать</span><span style=\" font-size:10pt; font-weight:600;\"> не менее 200 символов!</span></p><p><span style=\" font-size:10pt;\">Если вы хотите отправить фото вместе с письмом, перейдите на вкладку </span><span style=\" font-size:10pt; font-weight:600;\">&quot;Фото&quot;</span><span style=\" font-size:10pt;\"> и выберите нужные. </span></p><p><span style=\" font-size:10pt;\">В письме можно использовать HTML разметку, например </span></p><p><span style=\" font-size:10pt;\">&lt;b&gt;</span><span style=\" font-size:10pt; font-weight:600;\">этот текст</span><span style=\" font-size:10pt;\">&lt;/b&gt; будет виден в сообщении жирным шрифтом.</span></p></body></html>", None))
        self.plainTextEdit_letter_body.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Шаблоны писем</p></body></html>", None))
        self.plainTextEdit_letter_body.setPlainText(_translate("Dialog", "Пример письма №1. \n"
"\n"
"Если вставить в письмо переменную %name%, она будет автоматически заменена на имя мужчины. Письмо должно содержать не менее 200 символов\n"
"======\n"
"Пример письма №2. \n"
"\n"
"Обратите внимание на знаки рано (=) в конце письма. Так мы разделяем одно письмо от другого. Знаков разделения может быть любое количество.\n"
"======\n"
"Пример письма №3. \n"
"\n"
"Если вы хотите отправить фото вместе с письмом, перейдите на вкладку \"Фото\" и выберите нужные. \n"
"В письме можно использовать HTML разметку, например <b>этот текст</b> будет виден в сообщении жирным шрифтом.", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Отправка сообщения в чат ", None))
        self.plainTextEdit_msg.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Шаблоны сообщений</span></p><p><span style=\" font-size:10pt;\">Сюда вставляем шаблоны сообщений для отправки в чат. </span></p><p><span style=\" font-size:10pt;\">Обратите внимание на знаки равно</span><span style=\" font-size:10pt; font-weight:600;\"> &quot;=&quot;</span><span style=\" font-size:10pt;\"/><span style=\" font-size:10pt;\">в конце письма. Так мы разделяем одно письмо от другого. Знаков разделения может быть любое количество.</span></p><p><span style=\" font-size:10pt;\">Если вставить в письмо переменную </span><span style=\" font-size:10pt; font-weight:600;\">%name%</span><span style=\" font-size:10pt;\">, она будет автоматически заменена на имя мужчины.</span></p></body></html>", None))
        self.plainTextEdit_msg.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Шаблон сообщения в чат</p></body></html>", None))
        self.plainTextEdit_msg.setPlainText(_translate("Dialog", "Пример сообщения в чат №1. \n"
"\n"
"Обратите внимание на знаки равно (=) в конце письма. Так мы разделяем одно письмо от другого. Знаков разделения может быть любое количество. \n"
"========\n"
"Пример сообщения в чат №2. \n"
"\n"
"Если вставить в письмо переменную %name%, она будет автоматически заменена на имя мужчины.\n"
"========\n"
"Пример сообщения в чат №3. \n"
"\n"
"Обратите внимание на знаки равно (=) в конце письма. Так мы разделяем одно письмо от другого. Знаков разделения может быть любое количество. ", None))
        self.groupBox_6.setTitle(_translate("Dialog", "ЧАТ", None))
        self.plainTextEdit_chat_blacklist.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Черный список чата</span></p><p><span style=\" font-size:10pt;\"><br/>Сюда вставляем </span><span style=\" font-size:10pt; font-weight:600;\">id</span><span style=\" font-size:10pt;\"> мужчин, которым мы не желаем отправлять сообщения.</span></p><p><span style=\" font-size:10pt;\">Обратите внимание на запятые </span><span style=\" font-size:10pt; font-weight:600;\">&quot;,&quot;</span><span style=\" font-size:10pt;\"> после каждого id. Так мы разделяем один id от другого.</span></p><p><span style=\" font-size:10pt;\">Послк рассылки сыда автоматически заносятся id отправка для которых завершилась с ошибкой.</span></p></body></html>", None))
        self.plainTextEdit_chat_blacklist.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Черный список чата</p></body></html>", None))
        self.groupBox_8.setTitle(_translate("Dialog", "ПОКЛОННИКИ", None))
        self.plainTextEdit_admirer_blacklist.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Черный список поклонников</span></p><p><span style=\" font-size:10pt;\"><br/>Сюда вставляем </span><span style=\" font-size:10pt; font-weight:600;\">id</span><span style=\" font-size:10pt;\"> мужчин, которым мы не желаем отправлять сообщения.</span></p><p><span style=\" font-size:10pt;\">Обратите внимание на запятые </span><span style=\" font-size:10pt; font-weight:600;\">&quot;,&quot;</span><span style=\" font-size:10pt;\"> после каждого id. Так мы разделяем один id от другого.</span></p><p><span style=\" font-size:10pt;\">Послк рассылки сыда автоматически заносятся id отправка для которых завершилась с ошибкой.</span></p></body></html>", None))
        self.plainTextEdit_admirer_blacklist.setWhatsThis(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Черный список поклонников</span></p></body></html>", None))

import resource_rc
